"""create tickets

Revision ID: ef720fa92c78
Revises: 
Create Date: 2026-08-29 15:17:38.671786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef720fa92c78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'in_progress', 'in_review', 'done', name='ticket_status'), server_default='backlog', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('tickets')
    # Hand-added: drop_table leaves the enum TYPE behind, so a downgrade followed
    # by an upgrade would fail with "type ticket_status already exists".
    sa.Enum(name='ticket_status').drop(op.get_bind())
