"""create discussion room tables

Revision ID: f52211af4ab5
Revises: ef720fa92c78
Create Date: 2026-08-29

Written by hand rather than autogenerated: the database was unreachable at the
time (blank DB_* credentials), and autogenerate would not have produced the
persona seed anyway.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52211af4ab5'
down_revision: Union[str, Sequence[str], None] = 'ef720fa92c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    personas = op.create_table(
        'personas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'role',
            sa.Enum('architect', 'researcher', 'challenger', 'arbiter', name='persona_role'),
            nullable=False,
        ),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('avatar', sa.String(length=8), nullable=False),
        sa.Column('accent_color', sa.String(length=7), nullable=False),
        sa.Column('tagline', sa.String(length=120), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role'),
    )

    # The cast is seeded here rather than at startup so the four rows exist before
    # any message can reference them. Display data only — the system prompts stay
    # in app/core/personas.py.
    op.bulk_insert(
        personas,
        [
            {
                'role': 'architect',
                'name': 'Architect',
                'avatar': '\U0001F3D7️',
                'accent_color': '#6366f1',
                'tagline': 'Proposes the solution',
                'display_order': 1,
            },
            {
                'role': 'researcher',
                'name': 'Researcher',
                'avatar': '\U0001F4DA',
                'accent_color': '#14b8a6',
                'tagline': 'Brings the facts',
                'display_order': 2,
            },
            {
                'role': 'challenger',
                'name': 'Challenger',
                'avatar': '\U0001F9E8',
                'accent_color': '#f43f5e',
                'tagline': 'Tests the solution',
                'display_order': 3,
            },
            {
                'role': 'arbiter',
                'name': 'Arbiter',
                'avatar': '⚖️',
                'accent_color': '#f59e0b',
                'tagline': 'Makes the call',
                'display_order': 4,
            },
        ],
    )

    op.create_table(
        'conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column(
            'author_kind',
            sa.Enum('user', 'persona', 'document', name='message_author_kind'),
            nullable=False,
        ),
        sa.Column('persona_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('round_index', sa.Integer(), server_default='0', nullable=False),
        sa.Column('source_name', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['persona_id'], ['personas.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_messages_conversation_id_id', 'messages', ['conversation_id', 'id'])

    op.create_table(
        'ai_provider_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('model', sa.String(length=100), nullable=False),
        sa.Column('api_key', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('ai_provider_configs')
    op.drop_index('ix_messages_conversation_id_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('personas')
    # drop_table leaves the enum TYPEs behind, so a downgrade followed by an
    # upgrade would fail with "type already exists" — same trap as ticket_status.
    sa.Enum(name='message_author_kind').drop(op.get_bind())
    sa.Enum(name='persona_role').drop(op.get_bind())
